### ISSUE TITLE
Add validation for "СНИЛС" (RU-specific number)

### ISSUE THREAD

**Issue by gomzyakov** [gomzyakov/inn#37]

**Comment by paataD** [comment]
Алгоритм проверки контрольного числа КАРТОЧКИ ПЕНСИОННОГО СТРАХОВАНИЯ: Номер карточки пенсионного страхования (он же СНИЛС) проверяется на валидность контрольным числом. СНИЛС имеет вид: «XXX-XXX-XXX YY», где XXX—XXX-XXX — собственно номер, а YY — контрольное число. Проверка контрольного числа Страхового номера проводится только для номеров больше номера 001—001-998 Контрольное число СНИЛС рассчитывается следующим образом: Каждая цифра СНИЛС умножается на номер своей позиции (позиции отсчитываются с конца) Полученные произведения суммируются Если сумма меньше 100, то контрольное число равно самой сумме Если сумма равна 100 или 101, то контрольное число равно 00 Если сумма больше 101, то сумма делится нацело на 101 и контрольное число определяется остатком от деления аналогично пунктам 3 и 4. Примеры: Указан СНИЛС 112-233-445 95 Проверяем правильность контрольного числа: цифры номера 1 1 2 2 3 3 4 4 5 номер позиции 9 8 7 6 5 4 3 2 1 Сумма = 1х9 + 1х8 + 2х7 + 2х6 + 3х5 + 3х4 + 4х3 + 4х2 + 5х1 = 95 95 / !101! =95 Контрольное число 95 - указано верно.

**Comment by paataD** [comment]
preg_match_all('!\d!', '112-233-445 95', $matches);
$number =   (int) implode('', $matches[0]);

if(strlen($number) !== 11 ){
    echo 'Error wrong length!';
}
preg_match('/(\d{9})(\d{2})/i', $number, $innNumArr);

$controlSum = 0;
foreach(str_split($innNumArr[1]) as $i => $char){
    $controlSum += $char * (9 - $i);
}
if($controlSum <= 100 && $controlSum != $innNumArr[2] || $controlSum > 100 && $controlSum/101 != $innNumArr[2]) {
    echo 'Error wrong Sum!';
}

**Comment by gomzyakov** [comment]
Спасибо @paataD !

Если есть желание и время, можете оформить правки (из комментария выше) в PR :)
